<?php
/**
 * @file
 * Provides admin interface for handling the queue.
 * TODO: Fix bulk operations integration.
 * TODO: @See comments at top of Houston_Queue.
 */

/**
 * Implements hook_views_api().
 */
function houston_queue_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function houston_queue_menu() {
  $items = array();
  $items['admin/structure/houston/queue/%houston_queue_item/delete'] = array(
    'title' => 'Remove Item From Queue',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('houston_queue_delete_item_form', 4),
    // TODO: Some sort of access that checks for existance
    // should be implemented.
    'access arguments' => array('administer houston'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_views_bulk_operations_object_info().
 * TODO: Not sure if this is still available.
 */
function houston_queue_views_bulk_operations_object_info() {
  $object_info = array(
    'houston_queue_item' => array(
      'type' => 'houston_queue',
      'base_table' => 'houston_queue',
      'load' => 'houston_queue_item_load',
      'oid' => 'id',
      'title' => 'title',
    ),
  );
  return $object_info;
}

/**
 * Implements hook_action_info().
 */
function mymodule_action_info() {
  return array(
    'houston_queue_delete_action' => array(
      'description' => t('Delete Houston Queue Item'),
      'type' => 'houston_queue_item',
      'configurable' => FALSE,
      'hooks' => array(
        'houston_queue' => array('delete'),
      ),
    ),
  );
}

/**
 * Form for deleting items from the queue.
 *
 * Note: This could cause an issue if the queue is
 * currently running.
 */
function houston_queue_delete_item_form($form, &$form_state, $queue_item) {
  $form['qid'] = array(
    '#type' => 'value',
    '#value' => isset($queue_item->qid) ? $queue_item->qid : 0,
  );
  return confirm_form($form, t('Are you sure you want to delete this queue item?'), 'admin/structure/houston');
}

/**
 * Submission callback to delete a houston queu item.
 */
function houston_queue_delete_item_form_submit(&$form, &$form_state) {
  $queue_item = houston_queue_item_load($form_state['values']['qid']);
  if ($queue_item) {
    houston_queue_delete_action($queue_item);
  }
}

/**
 * Load a queue item by id.
 */
function houston_queue_item_load($qid) {
  $queue = houston_queue_get_full_houston_queue();
  return $queue->loadSingleQueueItem($qid);
}

/**
 * Load up a queue object from Houston one time.
 */
function houston_queue_get_full_houston_queue() {
  $queue = NULL;
  if (is_null($queue)) {
    $queue = houston_get_data_object('Houston_Queue');
  }
  return $queue;
}

/**
 * Core Action callback for queue item deletion.
 * TODO: Check if this works.
 */
function houston_queue_delete_action($queue_item, $context = NULL) {
  if ($queue_item) {
    $queue = houston_queue_get_full_houston_queue();
    $queue->deleteItemFromQueue($queue_item->qid);
  }
}

